language: "python"
sudo: "required"
services:
  - "docker"
before_install:
  - docker build -t meshfields/standalone-firefox .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
branch: master