language: "python"
sudo: "required"
services:
  - "docker"
before_install:
  - docker build -t meshfields/saveup-test-docker .
  - docker run -d -p 127.0.0.1:80:4567 meshfields/saveup-test-docker /bin/sh -c "cd /root/saveup-test-docker; npm start;"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
branch: master